apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: task1
spec:
  replicas: 10
  selector:
    matchLabels:
      app: task1
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: task1
    spec:
      containers:
      - name: task1
        image: steoconnor/task1kube
        ports:
        - containerPort: 5500
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: task1
spec:
  type: ClusterIP
  selector:
    app: task1
  ports:
  - protocol: TCP
    port: 5500
    targetPort: 5500